services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: redmine
      POSTGRES_DB: redmine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U redmine"]
      interval: 10s
      timeout: 5s
      retries: 5

  redmine:
    image: redmine
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3000"
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: secret
      REDMINE_DB_PORT: 5432
      # Enable CORS for API access
      RAILS_ENV: production
    volumes:
      - redmine_files:/usr/src/redmine/files
      - ./config/cors.rb:/usr/src/redmine/config/initializers/cors.rb
    restart: unless-stopped

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.yaml
    volumes:
      - ./swagger.yaml:/swagger/swagger.yaml

volumes:
  postgres_data:
  redmine_files:
